### ISSUE TITLE
Error Create Reconciliation

### ISSUE THREAD

**Issue by AlbertSutjipto** [Fortius-Solusi-Informatika/ClaraBug#13]
Error ketika membuat Reconciliation (Environment Local User):
1. Create New Reconciliation 
2. Isi Reconciliation Name
3. Add Reconsource untuk 2 sisi (Sisi A dan Sisi B)
4. Add Role ke User yang dipakai
5. Klik Save

[Error Create Reconciliation.docx](https://github.com/user-attachments/files/17899225/Error.Create.Reconciliation.docx)

**Comment by AlbertSutjipto** [comment]
Tambahan ketika cancel Reconciliation yang mau dibuat muncul error convertion.
<img width="534" alt="Error Create Reconciliation" src="https://github.com/user-attachments/assets/fe32c7f6-5db4-4441-8ad7-42410071c091">

**Comment by AlbertSutjipto** [comment]
Sudah berhasil terbuat namun reconsource hilang dan muncul error seperti ini.
![image](https://github.com/user-attachments/assets/154d5844-b426-4490-9903-1f9aea3d1464)

**Comment by samsoxu** [comment]
Sorry ko @AlbertSutjipto untuk errornya tolong di cek lagi, sudah ku coba untuk reproduce errornya tapi engga muncul errornya dan berhasil. Semisal udah solved juga di ko Albert boleh di Close aja, kalo engga tolong di sertakan lagi aja errornya:

---
### Environment
- Server: 34.101.177.26
- URl: vm-crs-new:100
- Database: 34.101.177.26,2402
- Web Browser: Google Chrome

### Screenshot (Create Reconciliation)
![image](https://github.com/user-attachments/assets/457611d0-92d6-418f-81ba-06efa7e05fb2)

### Screenshot (Recon Source)
![image](https://github.com/user-attachments/assets/f06a0e04-0613-44f6-8eb4-828aeee35609)
