### ISSUE TITLE
Diagram.aspx error: Conversion failed when converting the varchar value '693,214' to data type int.

### ISSUE THREAD

**Issue by etika-candra** [Fortius-Solusi-Informatika/ClaraBug#16]
Conversion failed when converting the varchar value '693,214' to data type int.

![image](https://github.com/user-attachments/assets/7502b5b0-7325-40d9-9e73-7b038a32e77e)

**Comment by samsoxu** [comment]
Mohon informasi dilengkapi dengan mengikuti referensi ini https://github.com/Fortius-Solusi-Informatika/ClaraBug/issues/1

**Comment by samsoxu** [comment]
@etika-candra Untuk bug nya sudah di Fix dengan bug yang lain. Mohon untuk di cek kembali
