### ISSUE TITLE
Bug : Menu VIew Match Today masih error dan tidak bisa dibuka karena out of memory

### ISSUE THREAD

**Issue by etika-candra** [Fortius-Solusi-Informatika/ClaraBug#17]
splusi akan dibuatkan dengan sistem paging sehingga bisa menampilkan data dalam jumlah yang banyak.

![image](https://github.com/user-attachments/assets/7c15a836-ea44-44aa-9c7f-d38022408ed0)

**Comment by samsoxu** [comment]
Solved dengan Paging
