### ISSUE TITLE
Bug: Menu Upload Report tidak memunculkan rekon apapun di dropdown menu

### ISSUE THREAD

**Issue by diorenato9** [Fortius-Solusi-Informatika/ClaraBug#20]
<h1>Description</h1>
Pada tampilan menu upload report, harusnya dropdown reconcilation menampilkan list rekonsiliasi. Tapi ini tidak.

<h1>Steps to Reproduce</h1>
Ke menu upload report, lalu coba klik dropdown reconciliation.

<h1> Expected Behavior </h1>
Dropdown reconciliation muncul

<h1> Actual Behavior </h1>
Dropdown recon tidak muncul

<h1> Screenshot </h1>
![image](https://github.com/user-attachments/assets/eb9f8dec-23dd-48cc-b919-d7ddc63e4971)

**Comment by Rexyonist** [comment]
Ini di url yang mana koh ? soalnya di dev, dropdownnya memunculkan rekon RTGS dan TELKOMSEL
