### ISSUE TITLE
Bug: Saat grouping by status di transaction finder, status O hilang.

### ISSUE THREAD

**Issue by diorenato9** [Fortius-Solusi-Informatika/ClaraBug#21]
<h1>Description</h1>
Pada saat melakukan search di transaction finder, ketika dicoba digroup berdasarkan status, hanya tampil status C. Padahal harusnya ada status O juga.

<h1>Steps to reproduce</h1>
Di menu transaction finder, search rekon sesuai parameter tertera di screenshot.

<h1>Expected Behavior</h1>
Status O tampil di grouping

<h1>Actual Behavior</h1>
Status O tidak tampil di grouping

<h1>Screenshot</h1>
![image](https://github.com/user-attachments/assets/2da2e9c8-f887-46c7-9286-6e3ceca02014)

<h1>Environment</h1>
CLARA [34:](http://34.101.177.26:100/)

**Comment by samsoxu** [comment]
Mohon informasi dilengkapi dengan mengikuti referensi ini https://github.com/Fortius-Solusi-Informatika/ClaraBug/issues/1

**Comment by diorenato9** [comment]
Informasi telah dilengkapi

**Comment by samsoxu** [comment]
Bug already fixed
