### ISSUE TITLE
Spasi Tidak Sesuai di Kolom Report Name di Report Module UI

### ISSUE THREAD

**Issue by md-pras** [Fortius-Solusi-Informatika/ClaraBug#22]
### Description
Spasi Tidak Sesuai di Kolom Report Name di Report Module UI
![image](https://github.com/user-attachments/assets/7ea62efd-a03e-43ce-899a-05bac58f506b)

### Steps to Reproduce

- Buka modul Report
- Perhatikan penempatan spasi sebelum tanda '-'

### Expected Behavior
Seharusnya sebelum tanda '-' ada spasi
![image](https://github.com/user-attachments/assets/c8119a58-17c3-4b1a-ae10-0fe3a034ca00)

**Comment by samsoxu** [comment]
@md-pras Untuk hal ini sebenarnya spasi sebelum tanda '-' masih ada, namun terlihat menghilang karna font yang digunakan
