### ISSUE TITLE
ISSUE Maping.aspx CLARA

### ISSUE THREAD

**Issue by savetheeart** [Fortius-Solusi-Informatika/ClaraBug#26]
Hi Developer CLARA, 

ada temuan bug saat ingin membuat maping baru pada CLARA

# Environment
Server: CLARADEMO / 10.87.87.242 
Web Browser: (Edge)
Clara Version/Patch: Patch20241217
Operating System: (Windows Server 2016 std)

# CLARA - Maping.aspx  

1. Function Search bar tidak berfungsi (image1)
2. Edit dan Save pada Configrasi yang sama tanpa perubhan apapun akan muncul error (image2)
3. Modify Loader Profile existing menjadi yang lain (image3) > save, error (image2)
4. kondisi sekarang ada 4 konfigurasi untuk 1 Load Profile, jika di modify 1 konfiguration. akan terupdate ke semua  (image4)
- Load Profile (LOAD TELKOMSEL PREPAID) 
- Konfiguration : - LOAD_TELKOMSEL_PREPAID_ROW, LOAD_TELKOMSEL_PREPAID_HEADER,LOAD_TELKOMSEL_PREPAID_SUSPECT_ROW,LOAD_TELKOMSEL_PREPAID__SUSPECT_HEADER)
5. Jika kondisi 4 sudah terpenuhi, saat modify kembali akan muncul error (image5)
6. Default Maping saat generate baru untuk Reports menjadi FixWidth (image6)

# SCRENSHOOTS

![image](https://github.com/user-attachments/assets/788b8126-62ce-4baf-81cb-def235c856e6) image1

![image](https://github.com/user-attachments/assets/b5cba620-e96c-4961-a025-f65e6da24a76) image2

![image](https://github.com/user-attachments/assets/81baca0d-281c-4910-976c-79a102dc2ab3) image3

![image](https://github.com/user-attachments/assets/73f442b3-113f-4878-8c47-340cde822c4d) image4

![image](https://github.com/user-attachments/assets/a505fe36-627d-48e3-a097-07384f0408e2) image5

![image](https://github.com/user-attachments/assets/67e12353-b204-4866-a42c-a05922cce8f9) image6

 # NOTES

Tidak ada error log yang muncul pada tabel MsiLogs

**Comment by Rexyonist** [comment]
- [ ] Function Search bar tidak berfungsi (image1)
- [ ] Edit dan Save pada Configrasi yang sama tanpa perubhan apapun akan muncul error (image2)
- [ ] Modify Loader Profile existing menjadi yang lain (image3) > save, error (image2)
- [ ] kondisi sekarang ada 4 konfigurasi untuk 1 Load Profile, jika di modify 1 konfiguration. akan terupdate ke semua (image4)
- [ ] Jika kondisi 4 sudah terpenuhi, saat modify kembali akan muncul error (image5)
- [ ] Default Maping saat generate baru untuk Reports menjadi FixWidth (image6)
