### ISSUE TITLE
[Bug] Status Job Monitor Selalu Success, Meskipun di SQL Job Failed

### ISSUE THREAD

**Issue by md-pras** [Fortius-Solusi-Informatika/ClaraBug#29]
### Description
Status **Job Monitor** Selalu Success, Meskipun di SQL Job Failed.

### Expected result
ketika ada Step yang failed di SQL Job, maka status di **Job Monitor** seharusnya **Failed**. Nice to have jika job di-run, statusnya **Processing** sampai SQL Job selesai eksekusi (**Success/Failed**).

### Actual result
Ketika job di-run, langsung terbentuk status **Success**, meskipun secara SQL job masih processing. dan ketika ada step yang failed, status di **Job Monitor** juga tetap **Success**.

**Comment by Rexyonist** [comment]
Duplicate Bug https://github.com/Fortius-Solusi-Informatika/ClaraBug/issues/23
