### ISSUE TITLE
Error ketika login http://vmi1378907:100/

### ISSUE THREAD

**Issue by etika-candra** [Fortius-Solusi-Informatika/ClaraBug#5]
Error ketika login http://vmi1378907:100/ :

![image](https://github.com/user-attachments/assets/802d5b45-a446-458e-b34f-966e103faf84)

**Comment by herdityapradipta** [comment]
Dear Etika,

Pop-up ini terjadi karena license memang belum diinstal.
Per pagi ini sudah saya install untuk licensenya,

Silahkan dicoba kembali.

Kalau sudah oke, tolong diclose ya :)

**Comment by etika-candra** [comment]
Dear Pak Herdit,

Ketika dicek kembali per siang ini setelah Pak Herdit apply license nya, pop up error sudah tidak muncul. Thanks.
![image](https://github.com/user-attachments/assets/b4f930c7-7c3b-4202-a428-a3ff6dd7288f)

Thanks and Regards,
Etika
