### ISSUE TITLE
Reconciliation Mapping Page - Penambahan Fitur agar Support Banyak XML dalam Satu Job

### ISSUE THREAD

**Issue by md-pras** [Fortius-Solusi-Informatika/ClaraBug#6]
### Description
Ketika membuat reconciliation mapping, data akan di-_insert_ ke tabel **tb_emsjob** dan **tb_emsjobconfiguration** secara bersamaan. Hal tersebut akan menjadi masalah jika satu job id di tabel **tb_emsjob** punya lebih dari satu configurasi XML di tabel **tb_emsjobconfiguration**. contoh _case_-nya adalah ketika satu job id di tabel **tb_emsjob** punya mappingan XML header dan mappingan detail di tabel **tb_emsjobconfiguration**.

### Expected Behavior
Terdapat opsi untuk support mapping banyak XML dalam satu job

**Comment by Rexyonist** [comment]
Recon Mapping

- [ ] Ilangin directories config
- [ ] library pada tab mapping ganti dropdown loader profile

Page baru loader profile -> nama page
- [ ] Pindahan dari directories config recon mapping
- [ ] -panel kiri ambil dari tb_emsjob (Support)
